server:
  context-path: /jeeplatform
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: @project.name@_${spring.profiles.active}


