server:
  context-path: /oa
  port: 8082
  error:
    path: /error
spring:
    #添加Thymeleaf配置，除了cache在项目没上线前建议关了，其它配置都可以不用配的，本博客只是列举一下有这些配置
  thymeleaf:
    # cache默认开启的，这里可以关了，项目上线之前，项目上线后可以开启
    cache: false
    # 这个prefix可以注释，因为默认就是templates的，您可以改成其它的自定义路径
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    # 指定一下编码为utf8
    encoding: UTF-8
    # context-type为text/html，也可以不指定，因为boot可以自动识别
    content-type: text/html


cas:
  server-login-url: http://127.0.0.1:8080/cas/login
  server-url-prefix: http://127.0.0.1:8080/cas
  client-host-url: http://127.0.0.1:8082


